apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-kalkulator-api
spec:
  ingresses:
    - "https://www.nav.no/arbeid/dagpenger/kalkulator-api/"
    - "https://dp-kalkulator-api.nais.oera.no/"
  sessionAffinity: ClientIP # Sticky Session for ingress controller to prevent 404 on rollout
  env:
    - name: API_GATEWAY_URL
      value: https://api-gw.oera.no/dp-reverse-proxy/
  replicas:
    min: 4
    max: 15
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 512Mi
  vault:
    paths:
      - kvPath: "kv/prod/sbs/dp-kalkulator-api/default"
        mountPath: "/var/run/secrets/nais.io/vault/"

